name: Docker

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v1.3.0

      - name: Build api image
        shell: bash
        run: docker build .

      - name: Build UI image
        shell: bash
        run: docker build ./frontend
